---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  tasks:
    # Instalar Docker y Kubernetes
    - import_tasks: common-tasks.yml

    # Step 3.2: Join the nodes to the Kubernetes cluster using below code.
    - name: Copy the join command to server location
      copy:
        src: "join"
        dest: /tmp/join-command.sh
        mode: 0777
      become: false

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh

  # Step 2.7: Setup a handler for checking Docker daemon using the below code.
  handlers:
    - name: docker status
      service: name=docker state=started
